# The Deliverfile allows you to store various iTunes Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

# 1
price_tier 0
# 2
app_review_information(
  first_name: "Rhodes",
  last_name: "Davis",
  phone_number: "205-493-0082",
  email_address: "rody.davis.jr@gmail.com",
  demo_user: "N/A",
  demo_password: "N/A",
  notes: "No demo account needed"
)
# 3
submission_information({    
    export_compliance_encryption_updated: false,
    export_compliance_uses_encryption: false,
    content_rights_contains_third_party_content: false,
    add_id_info_uses_idfa: false
})
# 4
automatic_release true
# 5
#app_icon './fastlane/metadata/AppIcon.png'
# 6
#app_rating_config_path "./fastlane/metadata/itunes_rating_config.json"