# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  
desc "Push a new beta build to TestFlight"
lane :beta do
  increment_build_number
  sh "cd ~/Projects/daily_nasa && flutter build ios"
  # build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
  upload_to_testflight
end

desc "Push a new release build to the App Store"
lane :release do
  increment_build_number
  sh "cd ~/Projects/daily_nasa && flutter build ios"
  # build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
  # upload_to_app_store

  upload_to_app_store(submit_for_review: true,
                          automatic_release: true,
                          skip_screenshots: true,
                          force: true)
end
end
